package org.chuck.deluge.ui.netbeans;

import java.awt.*;
import javax.swing.*;

/** NetBeans-compatible oscilloscope and spectrum visualizer. */
public class NetBeansVisualizerPanel extends javax.swing.JPanel {
  private MainViewModel viewModel;

  /** Creates new form NetBeansVisualizerPanel */
  public NetBeansVisualizerPanel() {
    initComponents();
    setBackground(Color.BLACK);
  }

  public void setViewModel(MainViewModel viewModel) {
    if (viewModel != null) {
      viewModel.addPropertyChangeListener(
          evt -> {
            if ("visBuffer".equals(evt.getPropertyName())
                || "compressorGr".equals(evt.getPropertyName())) {
              repaint();
            }
          });
    }
    this.viewModel = viewModel;
  }

  @Override
  protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    if (viewModel == null) return;

    Graphics2D g2 = (Graphics2D) g;
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    int w = getWidth();
    int h = getHeight();
    int quarterH = h / 4;

    // Draw Oscilloscope (Row 1)
    float[] data = viewModel.getVisBuffer();
    g2.setColor(new Color(0x00, 0xff, 0xcc));
    g2.setStroke(new BasicStroke(1.5f));

    if (data != null && data.length > 0) {
      int halfH = quarterH / 2;
      double xStep = (double) w / data.length;
      int lastX = 0;
      int lastY = halfH - (int) (data[0] * halfH * 0.9);

      for (int i = 1; i < data.length; i++) {
        int x = (int) (i * xStep);
        int y = halfH - (int) (data[i] * halfH * 0.9);
        g2.drawLine(lastX, lastY, x, y);
        lastX = x;
        lastY = y;
      }
    }

    // Draw Spectrum (Row 2) - Simulated
    g2.setColor(new Color(0x00, 0xaa, 0xff));
    int specY = quarterH + 10;
    int specH = quarterH - 20;
    for (int i = 0; i < 20; i++) {
      int barH =
          (int) ((Math.sin(i * 0.4 + System.currentTimeMillis() * 0.005) + 1.0) * (specH / 2.5));
      g2.fillRect(15 + i * (w - 30) / 20, specY + specH - barH, (w - 30) / 25, barH);
    }

    // Draw Waterfall (Row 3) - Simulated
    g2.setColor(new Color(0xff, 0x00, 0x55));
    int waterY = quarterH * 2 + 10;
    int waterH = quarterH - 20;
    for (int yOffset = 0; yOffset < waterH; yOffset += 2) {
      int intensity = (int) (Math.random() * 100 + 50);
      g2.setColor(new Color(intensity, 0, 255 - intensity, 100));
      g2.fillRect(15, waterY + yOffset, w - 30, 2);
    }

    // Draw Compressor GR Meter
    double gr = viewModel.getCompressorGr();
    g2.setColor(Color.ORANGE);
    int barH = (int) (gr * (h - 40));
    g2.fillRect(w - 12, h - 20 - barH, 8, barH);
    g2.setColor(Color.DARK_GRAY);
    g2.drawRect(w - 12, 20, 8, h - 40);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(new java.awt.Color(0, 0, 0));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE));
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
