package org.chuck.deluge.firmware2;

/**
 * Faithful port of the Deluge analog-square band-limited wavetables ({@code
 * util/lookuptables/analog_square.cpp} + the {@code analogSquareTables[20]} map in {@code
 * dsp/oscillators/basic_waves.cpp}). The {@code .bin} resources were generated byte-for-byte from
 * the C int16 arrays (big-endian shorts, matching {@link WavetableLoader}). Each table size is
 * {@code 2^magnitude + 1} where magnitude comes from {@link Oscillator#getTableNumber}
 * (13/12/11/10/9).
 */
public final class AnalogSquareLookupTables {
  private AnalogSquareLookupTables() {}

  private static short[] t(String name, int size) {
    return WavetableLoader.loadTable("/lookuptables/" + name + ".bin", size);
  }

  // Sizes per the C arrays: 8193=2^13+1, 4097=2^12+1, 2049=2^11+1, 1025=2^10+1, 513=2^9+1.
  public static final short[] analogSquare_1722 = t("analogSquare_1722", 8193);
  public static final short[] analogSquare_1217 = t("analogSquare_1217", 4097);
  public static final short[] analogSquare_861 = t("analogSquare_861", 4097);
  public static final short[] analogSquare_609 = t("analogSquare_609", 2049);
  public static final short[] analogSquare_431 = t("analogSquare_431", 2049);
  public static final short[] analogSquare_305 = t("analogSquare_305", 2049);
  public static final short[] analogSquare_215 = t("analogSquare_215", 2049);
  public static final short[] analogSquare_153 = t("analogSquare_153", 2049);
  public static final short[] analogSquare_109 = t("analogSquare_109", 2049);
  public static final short[] analogSquare_76 = t("analogSquare_76", 2049);
  public static final short[] analogSquare_53 = t("analogSquare_53", 2049);
  public static final short[] analogSquare_39 = t("analogSquare_39", 2049);
  public static final short[] analogSquare_27 = t("analogSquare_27", 2049);
  public static final short[] analogSquare_19 = t("analogSquare_19", 2049);
  public static final short[] analogSquare_13 = t("analogSquare_13", 1025);
  public static final short[] analogSquare_9 = t("analogSquare_9", 1025);
  public static final short[] analogSquare_7 = t("analogSquare_7", 1025);
  public static final short[] analogSquare_5 = t("analogSquare_5", 1025);
  public static final short[] analogSquare_3 = t("analogSquare_3", 513);
  public static final short[] analogSquare_1 = t("analogSquare_1", 513);

  /** C: {@code const int16_t* analogSquareTables[20]} (basic_waves.cpp). tableNumber -> table. */
  public static final short[][] analogSquareTables = {
    analogSquare_1722, analogSquare_1217, analogSquare_861, analogSquare_609,
    analogSquare_431, analogSquare_305, analogSquare_215, analogSquare_153,
    analogSquare_109, analogSquare_76, analogSquare_53, analogSquare_39,
    analogSquare_27, analogSquare_19, analogSquare_13, analogSquare_9,
    analogSquare_7, analogSquare_5, analogSquare_3, analogSquare_1
  };
}
