package org.chuck.deluge.firmware2;

/**
 * Faithful port of the Deluge analog-saw ("mystery synth") band-limited wavetables
 * ({@code util/lookuptables/mystery_synth_a_saw.cpp} + {@code mystery_synth_b_saw.cpp}) and the
 * {@code analogSawTables[20]} map in {@code dsp/oscillators/basic_waves.cpp}. The C map uses the
 * mysterySynthA tables for the low (more-harmonic) bands and mysterySynthB for the high bands.
 * {@code .bin} resources generated byte-for-byte from the C int16 arrays (big-endian).
 */
public final class AnalogSawLookupTables {
  private AnalogSawLookupTables() {}

  private static short[] t(String name, int size) {
    return WavetableLoader.loadTable("/lookuptables/" + name + ".bin", size);
  }

  // mysterySynthASaw_* (sizes: 1722=8193, 1217=4097, 861=4097, 609..153=2049)
  public static final short[] mysterySynthASaw_1722 = t("mysterySynthASaw_1722", 8193);
  public static final short[] mysterySynthASaw_1217 = t("mysterySynthASaw_1217", 4097);
  public static final short[] mysterySynthASaw_861 = t("mysterySynthASaw_861", 4097);
  public static final short[] mysterySynthASaw_609 = t("mysterySynthASaw_609", 2049);
  public static final short[] mysterySynthASaw_431 = t("mysterySynthASaw_431", 2049);
  public static final short[] mysterySynthASaw_305 = t("mysterySynthASaw_305", 2049);
  public static final short[] mysterySynthASaw_215 = t("mysterySynthASaw_215", 2049);
  public static final short[] mysterySynthASaw_153 = t("mysterySynthASaw_153", 2049);

  // mysterySynthBSaw_* (sizes: 109..19=2049, 13..5=1025, 3,1=513)
  public static final short[] mysterySynthBSaw_109 = t("mysterySynthBSaw_109", 2049);
  public static final short[] mysterySynthBSaw_76 = t("mysterySynthBSaw_76", 2049);
  public static final short[] mysterySynthBSaw_53 = t("mysterySynthBSaw_53", 2049);
  public static final short[] mysterySynthBSaw_39 = t("mysterySynthBSaw_39", 2049);
  public static final short[] mysterySynthBSaw_27 = t("mysterySynthBSaw_27", 2049);
  public static final short[] mysterySynthBSaw_19 = t("mysterySynthBSaw_19", 2049);
  public static final short[] mysterySynthBSaw_13 = t("mysterySynthBSaw_13", 1025);
  public static final short[] mysterySynthBSaw_9 = t("mysterySynthBSaw_9", 1025);
  public static final short[] mysterySynthBSaw_7 = t("mysterySynthBSaw_7", 1025);
  public static final short[] mysterySynthBSaw_5 = t("mysterySynthBSaw_5", 1025);
  public static final short[] mysterySynthBSaw_3 = t("mysterySynthBSaw_3", 513);
  public static final short[] mysterySynthBSaw_1 = t("mysterySynthBSaw_1", 513);

  /** C: {@code const int16_t* analogSawTables[20]} (basic_waves.cpp). tableNumber -> table. */
  public static final short[][] analogSawTables = {
    mysterySynthASaw_1722, mysterySynthASaw_1217, mysterySynthASaw_861, mysterySynthASaw_609,
    mysterySynthASaw_431, mysterySynthASaw_305, mysterySynthASaw_215, mysterySynthASaw_153,
    mysterySynthBSaw_109, mysterySynthBSaw_76, mysterySynthBSaw_53, mysterySynthBSaw_39,
    mysterySynthBSaw_27, mysterySynthBSaw_19, mysterySynthBSaw_13, mysterySynthBSaw_9,
    mysterySynthBSaw_7, mysterySynthBSaw_5, mysterySynthBSaw_3, mysterySynthBSaw_1
  };
}
