package org.deluge;

import org.deluge.shadow.core.ChuckArray;
import java.util.Arrays;

/**
 * Extracted StepData class from BridgeContract.java to reduce file complexity.
 */
final class BridgeStepData {
  static final int PATTERN_SIZE = BridgeContract.PATTERN_SIZE;

  // Global variables used by ChucK VM
  static final String G_PATTERN = BridgeContract.G_PATTERN;
  static final String G_VELOCITY = BridgeContract.G_VELOCITY;
  static final String G_GATE = BridgeContract.G_GATE;
  static final String G_PITCH = BridgeContract.G_PITCH;
  static final String G_PROBABILITY = BridgeContract.G_PROBABILITY;
  static final String G_ITERANCE = BridgeContract.G_ITERANCE;
  static final String G_FILL = BridgeContract.G_FILL;
  static final String G_STEP_FILTER = BridgeContract.G_STEP_FILTER;
  static final String G_STEP_RES = BridgeContract.G_STEP_RES;
  static final String G_STEP_FILTER_MODE = BridgeContract.G_STEP_FILTER_MODE;
  static final String G_STEP_PAN = BridgeContract.G_STEP_PAN;
  static final String G_STEP_DELAY = BridgeContract.G_STEP_DELAY;
  static final String G_STEP_REVERB = BridgeContract.G_STEP_REVERB;
  static final String G_STEP_MOD = BridgeContract.G_STEP_MOD;
  static final String G_STEP_START = BridgeContract.G_STEP_START;
  static final String G_STEP_END = BridgeContract.G_STEP_END;
  static final String G_STEP_HPF_FREQ = BridgeContract.G_STEP_HPF_FREQ;
  static final String G_STEP_HPF_RES = BridgeContract.G_STEP_HPF_RES;
  static final String G_STEP_MOD_RATE = BridgeContract.G_STEP_MOD_RATE;
  static final String G_STEP_MOD_DEPTH = BridgeContract.G_STEP_MOD_DEPTH;
  static final String G_STEP_OSC_A_VOL = BridgeContract.G_STEP_OSC_A_VOL;
  static final String G_STEP_OSC_B_VOL = BridgeContract.G_STEP_OSC_B_VOL;
  static final String G_STEP_NOISE_VOL = BridgeContract.G_STEP_NOISE_VOL;
  static final String G_STEP_PITCH = BridgeContract.G_STEP_PITCH;
  static final String G_STEP_VOLUME = BridgeContract.G_STEP_VOLUME;
  static final String G_STEP_ENV_0_ATTACK = BridgeContract.G_STEP_ENV_0_ATTACK;
  static final String G_STEP_ENV_0_DECAY = BridgeContract.G_STEP_ENV_0_DECAY;
  static final String G_STEP_ENV_0_SUSTAIN = BridgeContract.G_STEP_ENV_0_SUSTAIN;
  static final String G_STEP_ENV_0_RELEASE = BridgeContract.G_STEP_ENV_0_RELEASE;
  static final String G_STEP_ENV_1_ATTACK = BridgeContract.G_STEP_ENV_1_ATTACK;
  static final String G_STEP_ENV_1_DECAY = BridgeContract.G_STEP_ENV_1_DECAY;
  static final String G_STEP_ENV_1_SUSTAIN = BridgeContract.G_STEP_ENV_1_SUSTAIN;
  static final String G_STEP_ENV_1_RELEASE = BridgeContract.G_STEP_ENV_1_RELEASE;
  static final String G_STEP_ENV_2_ATTACK = BridgeContract.G_STEP_ENV_2_ATTACK;
  static final String G_STEP_ENV_2_DECAY = BridgeContract.G_STEP_ENV_2_DECAY;
  static final String G_STEP_ENV_2_SUSTAIN = BridgeContract.G_STEP_ENV_2_SUSTAIN;
  static final String G_STEP_ENV_2_RELEASE = BridgeContract.G_STEP_ENV_2_RELEASE;
  static final String G_STEP_ENV_3_ATTACK = BridgeContract.G_STEP_ENV_3_ATTACK;
  static final String G_STEP_ENV_3_DECAY = BridgeContract.G_STEP_ENV_3_DECAY;
  static final String G_STEP_ENV_3_SUSTAIN = BridgeContract.G_STEP_ENV_3_SUSTAIN;
  static final String G_STEP_ENV_3_RELEASE = BridgeContract.G_STEP_ENV_3_RELEASE;
  static final String G_STEP_LFO_0_RATE = BridgeContract.G_STEP_LFO_0_RATE;
  static final String G_STEP_LFO_0_DEPTH = BridgeContract.G_STEP_LFO_0_DEPTH;
  static final String G_STEP_LFO_1_RATE = BridgeContract.G_STEP_LFO_1_RATE;
  static final String G_STEP_LFO_1_DEPTH = BridgeContract.G_STEP_LFO_1_DEPTH;
  static final String G_STEP_LFO_2_RATE = BridgeContract.G_STEP_LFO_2_RATE;
  static final String G_STEP_LFO_2_DEPTH = BridgeContract.G_STEP_LFO_2_DEPTH;
  static final String G_STEP_LFO_3_RATE = BridgeContract.G_STEP_LFO_3_RATE;
  static final String G_STEP_LFO_3_DEPTH = BridgeContract.G_STEP_LFO_3_DEPTH;
  static final String G_STEP_ARP_RATE = BridgeContract.G_STEP_ARP_RATE;
  static final String G_STEP_ARP_GATE = BridgeContract.G_STEP_ARP_GATE;
  static final String G_STEP_FM_AMOUNT = BridgeContract.G_STEP_FM_AMOUNT;
  static final String G_STEP_FM_RATIO = BridgeContract.G_STEP_FM_RATIO;
  static final String G_STEP_MOD_FX_FEEDBACK = BridgeContract.G_STEP_MOD_FX_FEEDBACK;
  static final String G_STEP_COMP_ATTACK = BridgeContract.G_STEP_COMP_ATTACK;
  static final String G_STEP_COMP_RELEASE = BridgeContract.G_STEP_COMP_RELEASE;
  static final String G_STEP_PORTAMENTO = BridgeContract.G_STEP_PORTAMENTO;
  static final String G_STEP_STUTTER = BridgeContract.G_STEP_STUTTER;
  static final String G_STEP_BITCRUSH = BridgeContract.G_STEP_BITCRUSH;
  static final String G_STEP_SRR = BridgeContract.G_STEP_SRR;

  final int[] pattern = new int[PATTERN_SIZE];
  final float[] velocity = new float[PATTERN_SIZE];
  final float[] gate = new float[PATTERN_SIZE];
  final int[] pitch = new int[PATTERN_SIZE];
  final float[] probability = new float[PATTERN_SIZE];
  final int[] iterance = new int[PATTERN_SIZE];
  final float[] fill = new float[PATTERN_SIZE];
  final float[] stepFilter = new float[PATTERN_SIZE];
  final float[] stepRes = new float[PATTERN_SIZE];
  final int[] stepFilterMode = new int[PATTERN_SIZE];
  final float[] stepPan = new float[PATTERN_SIZE];
  final float[] stepDelay = new float[PATTERN_SIZE];
  final float[] stepReverb = new float[PATTERN_SIZE];
  final float[] stepMod = new float[PATTERN_SIZE];
  final float[] stepStart = new float[PATTERN_SIZE];
  final float[] stepEnd = new float[PATTERN_SIZE];
  final float[] stepHpfFreq = new float[PATTERN_SIZE];
  final float[] stepHpfRes = new float[PATTERN_SIZE];
  final float[] stepModRate = new float[PATTERN_SIZE];
  final float[] stepModDepth = new float[PATTERN_SIZE];
  final float[] stepOscAVol = new float[PATTERN_SIZE];
  final float[] stepOscBVol = new float[PATTERN_SIZE];
  final float[] stepNoiseVol = new float[PATTERN_SIZE];
  final float[] stepPitch = new float[PATTERN_SIZE];
  final float[] stepVolume = new float[PATTERN_SIZE];
  final float[] stepEnv0Attack = new float[PATTERN_SIZE];
  final float[] stepEnv0Decay = new float[PATTERN_SIZE];
  final float[] stepEnv0Sustain = new float[PATTERN_SIZE];
  final float[] stepEnv0Release = new float[PATTERN_SIZE];
  final float[] stepEnv1Attack = new float[PATTERN_SIZE];
  final float[] stepEnv1Decay = new float[PATTERN_SIZE];
  final float[] stepEnv1Sustain = new float[PATTERN_SIZE];
  final float[] stepEnv1Release = new float[PATTERN_SIZE];
  final float[] stepEnv2Attack = new float[PATTERN_SIZE];
  final float[] stepEnv2Decay = new float[PATTERN_SIZE];
  final float[] stepEnv2Sustain = new float[PATTERN_SIZE];
  final float[] stepEnv2Release = new float[PATTERN_SIZE];
  final float[] stepEnv3Attack = new float[PATTERN_SIZE];
  final float[] stepEnv3Decay = new float[PATTERN_SIZE];
  final float[] stepEnv3Sustain = new float[PATTERN_SIZE];
  final float[] stepEnv3Release = new float[PATTERN_SIZE];
  final float[] stepLfo0Rate = new float[PATTERN_SIZE];
  final float[] stepLfo0Depth = new float[PATTERN_SIZE];
  final float[] stepLfo1Rate = new float[PATTERN_SIZE];
  final float[] stepLfo1Depth = new float[PATTERN_SIZE];
  final float[] stepLfo2Rate = new float[PATTERN_SIZE];
  final float[] stepLfo2Depth = new float[PATTERN_SIZE];
  final float[] stepLfo3Rate = new float[PATTERN_SIZE];
  final float[] stepLfo3Depth = new float[PATTERN_SIZE];
  final float[] stepArpRate = new float[PATTERN_SIZE];
  final float[] stepArpGate = new float[PATTERN_SIZE];
  final float[] stepFmAmount = new float[PATTERN_SIZE];
  final float[] stepFmRatio = new float[PATTERN_SIZE];
  final float[] stepModFxFeedback = new float[PATTERN_SIZE];
  final float[] stepCompAttack = new float[PATTERN_SIZE];
  final float[] stepCompRelease = new float[PATTERN_SIZE];
  final float[] stepPortamento = new float[PATTERN_SIZE];
  final float[] stepStutter = new float[PATTERN_SIZE];
  final float[] stepBitcrush = new float[PATTERN_SIZE];
  final float[] stepSrr = new float[PATTERN_SIZE];

  void initDefaults() {
    for (int i = 0; i < PATTERN_SIZE; i++) {
      pattern[i] = 0;
      velocity[i] = 0.8f;
      gate[i] = 0.9f;
      pitch[i] = 0;
      probability[i] = 1f;
      iterance[i] = 0;
      fill[i] = 0f;
      stepFilter[i] = 0f;
      stepRes[i] = 0f;
      stepFilterMode[i] = -1;
      stepPan[i] = 0f;
      stepDelay[i] = 0f;
      stepReverb[i] = 0f;
      stepMod[i] = 0f;
      stepStart[i] = 0f;
      stepEnd[i] = 1f;
      stepHpfFreq[i] = 0f;
      stepHpfRes[i] = 0f;
      stepModRate[i] = 0f;
      stepModDepth[i] = 0f;
      stepOscAVol[i] = 1f;
      stepOscBVol[i] = 1f;
      stepNoiseVol[i] = 1f;
      stepPitch[i] = 0f;
      stepVolume[i] = 0f;
      stepEnv0Attack[i] = 0f;
      stepEnv0Decay[i] = 0f;
      stepEnv0Sustain[i] = 0f;
      stepEnv0Release[i] = 0f;
      stepEnv1Attack[i] = 0f;
      stepEnv1Decay[i] = 0f;
      stepEnv1Sustain[i] = 0f;
      stepEnv1Release[i] = 0f;
      stepEnv2Attack[i] = 0f;
      stepEnv2Decay[i] = 0f;
      stepEnv2Sustain[i] = 0f;
      stepEnv2Release[i] = 0f;
      stepEnv3Attack[i] = 0f;
      stepEnv3Decay[i] = 0f;
      stepEnv3Sustain[i] = 0f;
      stepEnv3Release[i] = 0f;
      stepLfo0Rate[i] = 0f;
      stepLfo0Depth[i] = 0f;
      stepLfo1Rate[i] = 0f;
      stepLfo1Depth[i] = 0f;
      stepLfo2Rate[i] = 0f;
      stepLfo2Depth[i] = 0f;
      stepLfo3Rate[i] = 0f;
      stepLfo3Depth[i] = 0f;
      stepArpRate[i] = 0f;
      stepArpGate[i] = 0f;
      stepFmAmount[i] = 0f;
      stepFmRatio[i] = 0f;
      stepModFxFeedback[i] = 0f;
      stepCompAttack[i] = 0f;
      stepCompRelease[i] = 0f;
      stepPortamento[i] = 0f;
      stepStutter[i] = 0f;
      stepBitcrush[i] = 0f;
      stepSrr[i] = 0f;
    }
  }

  void register(BridgeContract bridge) {
    bridge.setGlobalObject(G_PATTERN, new ChuckArray(pattern));
    bridge.setGlobalObject(G_VELOCITY, new ChuckArray(velocity));
    bridge.setGlobalObject(G_GATE, new ChuckArray(gate));
    bridge.setGlobalObject(G_PITCH, new ChuckArray(pitch));
    bridge.setGlobalObject(G_PROBABILITY, new ChuckArray(probability));
    bridge.setGlobalObject(G_ITERANCE, new ChuckArray(iterance));
    bridge.setGlobalObject(G_FILL, new ChuckArray(fill));
    bridge.setGlobalObject(G_STEP_FILTER, new ChuckArray(stepFilter));
    bridge.setGlobalObject(G_STEP_RES, new ChuckArray(stepRes));
    bridge.setGlobalObject(G_STEP_FILTER_MODE, new ChuckArray(stepFilterMode));
    bridge.setGlobalObject(G_STEP_PAN, new ChuckArray(stepPan));
    bridge.setGlobalObject(G_STEP_DELAY, new ChuckArray(stepDelay));
    bridge.setGlobalObject(G_STEP_REVERB, new ChuckArray(stepReverb));
    bridge.setGlobalObject(G_STEP_MOD, new ChuckArray(stepMod));
    bridge.setGlobalObject(G_STEP_START, new ChuckArray(stepStart));
    bridge.setGlobalObject(G_STEP_END, new ChuckArray(stepEnd));
    bridge.setGlobalObject(G_STEP_HPF_FREQ, new ChuckArray(stepHpfFreq));
    bridge.setGlobalObject(G_STEP_HPF_RES, new ChuckArray(stepHpfRes));
    bridge.setGlobalObject(G_STEP_MOD_RATE, new ChuckArray(stepModRate));
    bridge.setGlobalObject(G_STEP_MOD_DEPTH, new ChuckArray(stepModDepth));
    bridge.setGlobalObject(G_STEP_OSC_A_VOL, new ChuckArray(stepOscAVol));
    bridge.setGlobalObject(G_STEP_OSC_B_VOL, new ChuckArray(stepOscBVol));
    bridge.setGlobalObject(G_STEP_NOISE_VOL, new ChuckArray(stepNoiseVol));
    bridge.setGlobalObject(G_STEP_PITCH, new ChuckArray(stepPitch));
    bridge.setGlobalObject(G_STEP_VOLUME, new ChuckArray(stepVolume));
    bridge.setGlobalObject(G_STEP_ENV_0_ATTACK, new ChuckArray(stepEnv0Attack));
    bridge.setGlobalObject(G_STEP_ENV_0_DECAY, new ChuckArray(stepEnv0Decay));
    bridge.setGlobalObject(G_STEP_ENV_0_SUSTAIN, new ChuckArray(stepEnv0Sustain));
    bridge.setGlobalObject(G_STEP_ENV_0_RELEASE, new ChuckArray(stepEnv0Release));
    bridge.setGlobalObject(G_STEP_ENV_1_ATTACK, new ChuckArray(stepEnv1Attack));
    bridge.setGlobalObject(G_STEP_ENV_1_DECAY, new ChuckArray(stepEnv1Decay));
    bridge.setGlobalObject(G_STEP_ENV_1_SUSTAIN, new ChuckArray(stepEnv1Sustain));
    bridge.setGlobalObject(G_STEP_ENV_1_RELEASE, new ChuckArray(stepEnv1Release));
    bridge.setGlobalObject(G_STEP_ENV_2_ATTACK, new ChuckArray(stepEnv2Attack));
    bridge.setGlobalObject(G_STEP_ENV_2_DECAY, new ChuckArray(stepEnv2Decay));
    bridge.setGlobalObject(G_STEP_ENV_2_SUSTAIN, new ChuckArray(stepEnv2Sustain));
    bridge.setGlobalObject(G_STEP_ENV_2_RELEASE, new ChuckArray(stepEnv2Release));
    bridge.setGlobalObject(G_STEP_ENV_3_ATTACK, new ChuckArray(stepEnv3Attack));
    bridge.setGlobalObject(G_STEP_ENV_3_DECAY, new ChuckArray(stepEnv3Decay));
    bridge.setGlobalObject(G_STEP_ENV_3_SUSTAIN, new ChuckArray(stepEnv3Sustain));
    bridge.setGlobalObject(G_STEP_ENV_3_RELEASE, new ChuckArray(stepEnv3Release));
    bridge.setGlobalObject(G_STEP_LFO_0_RATE, new ChuckArray(stepLfo0Rate));
    bridge.setGlobalObject(G_STEP_LFO_0_DEPTH, new ChuckArray(stepLfo0Depth));
    bridge.setGlobalObject(G_STEP_LFO_1_RATE, new ChuckArray(stepLfo1Rate));
    bridge.setGlobalObject(G_STEP_LFO_1_DEPTH, new ChuckArray(stepLfo1Depth));
    bridge.setGlobalObject(G_STEP_LFO_2_RATE, new ChuckArray(stepLfo2Rate));
    bridge.setGlobalObject(G_STEP_LFO_2_DEPTH, new ChuckArray(stepLfo2Depth));
    bridge.setGlobalObject(G_STEP_LFO_3_RATE, new ChuckArray(stepLfo3Rate));
    bridge.setGlobalObject(G_STEP_LFO_3_DEPTH, new ChuckArray(stepLfo3Depth));
    bridge.setGlobalObject(G_STEP_ARP_RATE, new ChuckArray(stepArpRate));
    bridge.setGlobalObject(G_STEP_ARP_GATE, new ChuckArray(stepArpGate));
    bridge.setGlobalObject(G_STEP_FM_AMOUNT, new ChuckArray(stepFmAmount));
    bridge.setGlobalObject(G_STEP_FM_RATIO, new ChuckArray(stepFmRatio));
    bridge.setGlobalObject(G_STEP_MOD_FX_FEEDBACK, new ChuckArray(stepModFxFeedback));
    bridge.setGlobalObject(G_STEP_COMP_ATTACK, new ChuckArray(stepCompAttack));
    bridge.setGlobalObject(G_STEP_COMP_RELEASE, new ChuckArray(stepCompRelease));
    bridge.setGlobalObject(G_STEP_PORTAMENTO, new ChuckArray(stepPortamento));
    bridge.setGlobalObject(G_STEP_STUTTER, new ChuckArray(stepStutter));
    bridge.setGlobalObject(G_STEP_BITCRUSH, new ChuckArray(stepBitcrush));
    bridge.setGlobalObject(G_STEP_SRR, new ChuckArray(stepSrr));
  }
}
