package org.deluge;

import org.deluge.shadow.core.ChuckArray;

/**
 * Extracted KitData class from BridgeContract.java to reduce file complexity.
 */
final class BridgeKitData {
  static final int TRACKS = BridgeContract.TRACKS;
  static final int MAX_CABLES_PER_TRACK = BridgeContract.MAX_CABLES_PER_TRACK;

  // Global variables used by ChucK VM
  static final String G_KIT_ATTACK = BridgeContract.G_KIT_ATTACK;
  static final String G_KIT_DECAY = BridgeContract.G_KIT_DECAY;
  static final String G_KIT_SUSTAIN = BridgeContract.G_KIT_SUSTAIN;
  static final String G_KIT_RELEASE = BridgeContract.G_KIT_RELEASE;
  static final String G_KIT_PITCH = BridgeContract.G_KIT_PITCH;
  static final String G_KIT_REVERSE = BridgeContract.G_KIT_REVERSE;
  static final String G_KIT_MUTE_GROUP = BridgeContract.G_KIT_MUTE_GROUP;
  static final String G_KIT_LPF_MODE = BridgeContract.G_KIT_LPF_MODE;
  static final String G_KIT_LPF_MORPH = BridgeContract.G_KIT_LPF_MORPH;
  static final String G_KIT_LPF_DRIVE = BridgeContract.G_KIT_LPF_DRIVE;
  static final String G_KIT_LPF_NOTCH = BridgeContract.G_KIT_LPF_NOTCH;
  static final String G_KIT_MAX_VOICES = BridgeContract.G_KIT_MAX_VOICES;
  static final String G_KIT_POLYPHONY = BridgeContract.G_KIT_POLYPHONY;
  static final String G_KIT_EQ_BASS = BridgeContract.G_KIT_EQ_BASS;
  static final String G_KIT_EQ_TREBLE = BridgeContract.G_KIT_EQ_TREBLE;
  static final String G_KIT_SIDECHAIN = BridgeContract.G_KIT_SIDECHAIN;
  static final String G_KIT_MOD_FX_TYPE = BridgeContract.G_KIT_MOD_FX_TYPE;
  static final String G_KIT_MOD_FX_RATE = BridgeContract.G_KIT_MOD_FX_RATE;
  static final String G_KIT_MOD_FX_DEPTH = BridgeContract.G_KIT_MOD_FX_DEPTH;
  static final String G_KIT_MOD_FX_OFFSET = BridgeContract.G_KIT_MOD_FX_OFFSET;
  static final String G_KIT_MOD_FX_FEEDBACK = BridgeContract.G_KIT_MOD_FX_FEEDBACK;
  static final String G_KIT_HPF_FREQ = BridgeContract.G_KIT_HPF_FREQ;
  static final String G_KIT_HPF_RES = BridgeContract.G_KIT_HPF_RES;
  static final String G_KIT_HPF_MORPH = BridgeContract.G_KIT_HPF_MORPH;
  static final String G_KIT_HPF_MODE = BridgeContract.G_KIT_HPF_MODE;
  static final String G_KIT_HPF_FM = BridgeContract.G_KIT_HPF_FM;
  static final String G_KIT_OSC2_TYPE = BridgeContract.G_KIT_OSC2_TYPE;
  static final String G_KIT_UNISON_NUM = BridgeContract.G_KIT_UNISON_NUM;
  static final String G_KIT_UNISON_DETUNE = BridgeContract.G_KIT_UNISON_DETUNE;
  static final String G_KIT_UNISON_SPREAD = BridgeContract.G_KIT_UNISON_SPREAD;
  static final String G_KIT_WAVE_INDEX = BridgeContract.G_KIT_WAVE_INDEX;
  static final String G_KIT_COMP_ATTACK = BridgeContract.G_KIT_COMP_ATTACK;
  static final String G_KIT_COMP_RELEASE = BridgeContract.G_KIT_COMP_RELEASE;
  static final String G_KIT_COMP_BLEND = BridgeContract.G_KIT_COMP_BLEND;
  static final String G_KIT_COMP_RATIO = BridgeContract.G_KIT_COMP_RATIO;
  static final String G_KIT_COMP_SIDECHAIN_HPF = BridgeContract.G_KIT_COMP_SIDECHAIN_HPF;
  static final String G_KIT_DELAY_RATE = BridgeContract.G_KIT_DELAY_RATE;
  static final String G_KIT_DELAY_FB = BridgeContract.G_KIT_DELAY_FB;
  static final String G_KIT_DELAY_PINGPONG = BridgeContract.G_KIT_DELAY_PINGPONG;
  static final String G_KIT_DELAY_ANALOG = BridgeContract.G_KIT_DELAY_ANALOG;
  static final String G_KIT_REVERB_AMOUNT = BridgeContract.G_KIT_REVERB_AMOUNT;
  static final String G_KIT_COMP_THRESHOLD = BridgeContract.G_KIT_COMP_THRESHOLD;
  static final String G_KIT_COMP_SYNC_LEVEL = BridgeContract.G_KIT_COMP_SYNC_LEVEL;
  static final String G_KIT_SIDECHAIN_SYNC_LEVEL = BridgeContract.G_KIT_SIDECHAIN_SYNC_LEVEL;
  static final String G_KIT_SIDECHAIN_SYNC_TYPE = BridgeContract.G_KIT_SIDECHAIN_SYNC_TYPE;
  static final String G_KIT_SIDECHAIN_ATTACK = BridgeContract.G_KIT_SIDECHAIN_ATTACK;
  static final String G_KIT_SIDECHAIN_RELEASE = BridgeContract.G_KIT_SIDECHAIN_RELEASE;
  static final String G_KIT_VOLUME = BridgeContract.G_KIT_VOLUME;
  static final String G_KIT_PAN = BridgeContract.G_KIT_PAN;
  static final String G_KIT_NOISE_VOL = BridgeContract.G_KIT_NOISE_VOL;
  static final String G_KIT_STUTTER_RATE = BridgeContract.G_KIT_STUTTER_RATE;
  static final String G_KIT_SAMPLE_RATE_RED = BridgeContract.G_KIT_SAMPLE_RATE_RED;
  static final String G_KIT_BITCRUSH = BridgeContract.G_KIT_BITCRUSH;
  static final String G_KIT_PC_COUNT = BridgeContract.G_KIT_PC_COUNT;
  static final String G_KIT_PC_SOURCE = BridgeContract.G_KIT_PC_SOURCE;
  static final String G_KIT_PC_DEST = BridgeContract.G_KIT_PC_DEST;
  static final String G_KIT_PC_AMOUNT = BridgeContract.G_KIT_PC_AMOUNT;
  static final String G_KIT_PC_POLARITY = BridgeContract.G_KIT_PC_POLARITY;

  final float[] kitAttack = new float[TRACKS];
  final float[] kitDecay = new float[TRACKS];
  final float[] kitSustain = new float[TRACKS];
  final float[] kitRelease = new float[TRACKS];
  final float[] kitPitch = new float[TRACKS];
  final int[] kitReverse = new int[TRACKS];
  final int[] kitMuteGroup = new int[TRACKS];
  final int[] kitLpfMode = new int[TRACKS];
  final float[] kitLpfMorph = new float[TRACKS];
  final float[] kitLpfDrive = new float[TRACKS];
  final int[] kitLpfNotch = new int[TRACKS];
  final int[] kitMaxVoices = new int[TRACKS];
  final int[] kitPolyphony = new int[TRACKS];
  final float[] kitEqBass = new float[TRACKS];
  final float[] kitEqTreble = new float[TRACKS];
  final float[] kitSidechain = new float[TRACKS];
  final int[] kitModFxType = new int[TRACKS];
  final float[] kitModFxRate = new float[TRACKS];
  final float[] kitModFxDepth = new float[TRACKS];
  final float[] kitModFxOffset = new float[TRACKS];
  final float[] kitModFxFeedback = new float[TRACKS];
  final float[] kitHpfFreq = new float[TRACKS];
  final float[] kitHpfRes = new float[TRACKS];
  final float[] kitHpfMorph = new float[TRACKS];
  final int[] kitHpfMode = new int[TRACKS];
  final float[] kitHpfFm = new float[TRACKS];
  final int[] kitOsc2Type = new int[TRACKS];
  final int[] kitUnisonNum = new int[TRACKS];
  final float[] kitUnisonDetune = new float[TRACKS];
  final float[] kitUnisonSpread = new float[TRACKS];
  final float[] kitWaveIndex = new float[TRACKS];
  final float[] kitCompressorAttackArr = new float[TRACKS];
  final float[] kitCompressorReleaseArr = new float[TRACKS];
  final float[] kitCompressorBlendArr = new float[TRACKS];
  final float[] kitCompressorRatioArr = new float[TRACKS];
  final float[] kitCompressorSidechainHpfArr = new float[TRACKS];
  final float[] kitDelayRate = new float[TRACKS];
  final float[] kitDelayFb = new float[TRACKS];
  final int[] kitDelayPingpong = new int[TRACKS];
  final int[] kitDelayAnalog = new int[TRACKS];
  final float[] kitReverbAmount = new float[TRACKS];
  final float[] kitCompThreshold = new float[TRACKS];
  final int[] kitCompSyncLevel = new int[TRACKS];
  final int[] kitSidechainSyncLevel = new int[TRACKS];
  final int[] kitSidechainSyncType = new int[TRACKS];
  final float[] kitSidechainAttack = new float[TRACKS];
  final float[] kitSidechainRelease = new float[TRACKS];
  final float[] kitVolume = new float[TRACKS];
  final float[] kitPan = new float[TRACKS];
  final float[] kitNoiseVol = new float[TRACKS];
  final float[] kitStutterRate = new float[TRACKS];
  final float[] kitSampleRateRed = new float[TRACKS];
  final float[] kitBitCrush = new float[TRACKS];
  final int[] kitPcCount = new int[TRACKS];
  final int[] kitPcSource = new int[TRACKS * MAX_CABLES_PER_TRACK];
  final int[] kitPcDest = new int[TRACKS * MAX_CABLES_PER_TRACK];
  final float[] kitPcAmount = new float[TRACKS * MAX_CABLES_PER_TRACK];
  final int[] kitPcPolarity = new int[TRACKS * MAX_CABLES_PER_TRACK];

  void initDefaults() {
    for (int t = 0; t < TRACKS; t++) {
      kitAttack[t] = 0.001f;
      kitDecay[t] = 0.1f;
      kitSustain[t] = 0.8f;
      kitRelease[t] = 0.2f;
      kitPitch[t] = 0f;
      kitReverse[t] = 0;
      kitMuteGroup[t] = 0;
      kitLpfMode[t] = 0;
      kitLpfMorph[t] = 0f;
      kitLpfDrive[t] = 1.0f;
      kitLpfNotch[t] = 0;
      kitMaxVoices[t] = 8;
      kitPolyphony[t] = 0;
      kitEqBass[t] = 0f;
      kitEqTreble[t] = 0f;
      kitSidechain[t] = 0f;
      kitModFxType[t] = 0;
      kitModFxRate[t] = 0.3f;
      kitModFxDepth[t] = 0.3f;
      kitModFxOffset[t] = 0f;
      kitModFxFeedback[t] = 0f;
      kitHpfFreq[t] = 20f;
      kitHpfRes[t] = 0f;
      kitHpfMorph[t] = 0f;
      kitHpfMode[t] = 0;
      kitHpfFm[t] = 0f;
      kitOsc2Type[t] = 0;
      kitUnisonNum[t] = 1;
      kitUnisonDetune[t] = 0f;
      kitUnisonSpread[t] = 0f;
      kitWaveIndex[t] = 0f;
      kitCompressorAttackArr[t] = 0f;
      kitCompressorReleaseArr[t] = 0f;
      kitCompressorBlendArr[t] = 0f;
      kitCompressorRatioArr[t] = 0.5f;
      kitCompressorSidechainHpfArr[t] = 0f;
      kitDelayRate[t] = 0f;
      kitDelayFb[t] = 0f;
      kitDelayPingpong[t] = 0;
      kitDelayAnalog[t] = 0;
      kitReverbAmount[t] = 0f;
      kitCompThreshold[t] = 0f;
      kitCompSyncLevel[t] = 0;
      kitSidechainSyncLevel[t] = 0;
      kitSidechainSyncType[t] = 0;
      kitSidechainAttack[t] = 0f;
      kitSidechainRelease[t] = 0f;
      kitVolume[t] = 0.5f;
      kitPan[t] = 0f;
      kitNoiseVol[t] = 0f;
      kitStutterRate[t] = 0f;
      kitSampleRateRed[t] = 0f;
      kitBitCrush[t] = 0f;
      kitPcCount[t] = 0;
    }
    for (int c = 0; c < TRACKS * MAX_CABLES_PER_TRACK; c++) {
      kitPcSource[c] = -1;
      kitPcDest[c] = -1;
      kitPcAmount[c] = 0f;
      kitPcPolarity[c] = 0;
    }
  }

  void register(BridgeContract bridge) {
    bridge.setGlobalObject(G_KIT_ATTACK, new ChuckArray(kitAttack));
    bridge.setGlobalObject(G_KIT_DECAY, new ChuckArray(kitDecay));
    bridge.setGlobalObject(G_KIT_SUSTAIN, new ChuckArray(kitSustain));
    bridge.setGlobalObject(G_KIT_RELEASE, new ChuckArray(kitRelease));
    bridge.setGlobalObject(G_KIT_PITCH, new ChuckArray(kitPitch));
    bridge.setGlobalObject(G_KIT_REVERSE, new ChuckArray(kitReverse));
    bridge.setGlobalObject(G_KIT_MUTE_GROUP, new ChuckArray(kitMuteGroup));
    bridge.setGlobalObject(G_KIT_LPF_MODE, new ChuckArray(kitLpfMode));
    bridge.setGlobalObject(G_KIT_LPF_MORPH, new ChuckArray(kitLpfMorph));
    bridge.setGlobalObject(G_KIT_LPF_DRIVE, new ChuckArray(kitLpfDrive));
    bridge.setGlobalObject(G_KIT_LPF_NOTCH, new ChuckArray(kitLpfNotch));
    bridge.setGlobalObject(G_KIT_MAX_VOICES, new ChuckArray(kitMaxVoices));
    bridge.setGlobalObject(G_KIT_POLYPHONY, new ChuckArray(kitPolyphony));
    bridge.setGlobalObject(G_KIT_EQ_BASS, new ChuckArray(kitEqBass));
    bridge.setGlobalObject(G_KIT_EQ_TREBLE, new ChuckArray(kitEqTreble));
    bridge.setGlobalObject(G_KIT_SIDECHAIN, new ChuckArray(kitSidechain));
    bridge.setGlobalObject(G_KIT_MOD_FX_TYPE, new ChuckArray(kitModFxType));
    bridge.setGlobalObject(G_KIT_MOD_FX_RATE, new ChuckArray(kitModFxRate));
    bridge.setGlobalObject(G_KIT_MOD_FX_DEPTH, new ChuckArray(kitModFxDepth));
    bridge.setGlobalObject(G_KIT_MOD_FX_OFFSET, new ChuckArray(kitModFxOffset));
    bridge.setGlobalObject(G_KIT_MOD_FX_FEEDBACK, new ChuckArray(kitModFxFeedback));
    bridge.setGlobalObject(G_KIT_HPF_FREQ, new ChuckArray(kitHpfFreq));
    bridge.setGlobalObject(G_KIT_HPF_RES, new ChuckArray(kitHpfRes));
    bridge.setGlobalObject(G_KIT_HPF_MORPH, new ChuckArray(kitHpfMorph));
    bridge.setGlobalObject(G_KIT_HPF_MODE, new ChuckArray(kitHpfMode));
    bridge.setGlobalObject(G_KIT_HPF_FM, new ChuckArray(kitHpfFm));
    bridge.setGlobalObject(G_KIT_OSC2_TYPE, new ChuckArray(kitOsc2Type));
    bridge.setGlobalObject(G_KIT_UNISON_NUM, new ChuckArray(kitUnisonNum));
    bridge.setGlobalObject(G_KIT_UNISON_DETUNE, new ChuckArray(kitUnisonDetune));
    bridge.setGlobalObject(G_KIT_UNISON_SPREAD, new ChuckArray(kitUnisonSpread));
    bridge.setGlobalObject(G_KIT_WAVE_INDEX, new ChuckArray(kitWaveIndex));
    bridge.setGlobalObject(G_KIT_COMP_ATTACK, new ChuckArray(kitCompressorAttackArr));
    bridge.setGlobalObject(G_KIT_COMP_RELEASE, new ChuckArray(kitCompressorReleaseArr));
    bridge.setGlobalObject(G_KIT_COMP_BLEND, new ChuckArray(kitCompressorBlendArr));
    bridge.setGlobalObject(G_KIT_COMP_RATIO, new ChuckArray(kitCompressorRatioArr));
    bridge.setGlobalObject(G_KIT_COMP_SIDECHAIN_HPF, new ChuckArray(kitCompressorSidechainHpfArr));
    bridge.setGlobalObject(G_KIT_DELAY_RATE, new ChuckArray(kitDelayRate));
    bridge.setGlobalObject(G_KIT_DELAY_FB, new ChuckArray(kitDelayFb));
    bridge.setGlobalObject(G_KIT_DELAY_PINGPONG, new ChuckArray(kitDelayPingpong));
    bridge.setGlobalObject(G_KIT_DELAY_ANALOG, new ChuckArray(kitDelayAnalog));
    bridge.setGlobalObject(G_KIT_REVERB_AMOUNT, new ChuckArray(kitReverbAmount));
    bridge.setGlobalObject(G_KIT_COMP_THRESHOLD, new ChuckArray(kitCompThreshold));
    bridge.setGlobalObject(G_KIT_COMP_SYNC_LEVEL, new ChuckArray(kitCompSyncLevel));
    bridge.setGlobalObject(G_KIT_SIDECHAIN_SYNC_LEVEL, new ChuckArray(kitSidechainSyncLevel));
    bridge.setGlobalObject(G_KIT_SIDECHAIN_SYNC_TYPE, new ChuckArray(kitSidechainSyncType));
    bridge.setGlobalObject(G_KIT_SIDECHAIN_ATTACK, new ChuckArray(kitSidechainAttack));
    bridge.setGlobalObject(G_KIT_SIDECHAIN_RELEASE, new ChuckArray(kitSidechainRelease));
    bridge.setGlobalObject(G_KIT_VOLUME, new ChuckArray(kitVolume));
    bridge.setGlobalObject(G_KIT_PAN, new ChuckArray(kitPan));
    bridge.setGlobalObject(G_KIT_NOISE_VOL, new ChuckArray(kitNoiseVol));
    bridge.setGlobalObject(G_KIT_STUTTER_RATE, new ChuckArray(kitStutterRate));
    bridge.setGlobalObject(G_KIT_SAMPLE_RATE_RED, new ChuckArray(kitSampleRateRed));
    bridge.setGlobalObject(G_KIT_BITCRUSH, new ChuckArray(kitBitCrush));
    bridge.setGlobalObject(G_KIT_PC_COUNT, new ChuckArray(kitPcCount));
    bridge.setGlobalObject(G_KIT_PC_SOURCE, new ChuckArray(kitPcSource));
    bridge.setGlobalObject(G_KIT_PC_DEST, new ChuckArray(kitPcDest));
    bridge.setGlobalObject(G_KIT_PC_AMOUNT, new ChuckArray(kitPcAmount));
    bridge.setGlobalObject(G_KIT_PC_POLARITY, new ChuckArray(kitPcPolarity));
  }
}
